#!/bin/bash

install_program () {
  read -p "Do you want to install $1? (y/n): " -r
  case $REPLY in
    y|Y )
      sudo apt install "$1" -y
    ;;
  esac
  printf "\n"
}

install_program "cmatrix"
install_program "sl"
install_program "neofetch"

add_server () {
  SERVER="$1"
  read -p "Do you want to add ssh keys to $SERVER? (y/n): " -r
  case $REPLY in
    y|Y )
      if ! test -f "$HOME/.ssh/id_rsa"; then
        echo "Creating a ssh key pair"
        printf "\n\n\n" | ssh-keygen
      fi

      ssh-copy-id "$SERVER"
    ;;
  esac
  printf "\n"
}

add_server "ateigen@data.cs.purdue.edu"
add_server "ateigen@scholar.rcac.purdue.edu"

append_bashrc () {
  if ! grep -q "$1" "$HOME/.bashrc"; then
    read -p "Add $1 to $HOME/.bashrc? (y/n): " -r
    case "$REPLY" in
      y|Y )
        printf "$1\n" >> ~/.bashrc
      ;;
    esac
    printf "\n"
  fi
}

append_bashrc "alias data='ssh ateigen@data.cs.purdue.edu'"
append_bashrc "alias cuda='ssh ateigen@cuda.cs.purdue.edu'"
append_bashrc "alias r='ssh scholar.rcac.purdue.edu'"
append_bashrc "alias ls='/usr/bin/ls -F'"
append_bashrc "alias ll='/usr/bin/ls -lh'"

append_nanorc () {
  if ! grep -q "$1" "$HOME/.nanorc"; then
    read -p "Add $1 to $HOME/.nanorc? (y/n): " -r
    case "$REPLY" in
      y|Y )
        printf "$1\n" >> ~/.nanorc
      ;;
    esac
    printf "\n"
  fi
}

append_nanorc "set tabstospaces"
append_nanorc "set tabsize 2"

exit 0
